# Generated by Django 3.2.15 on 2022-08-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'AboutUs',
            },
        ),
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('companyName', models.CharField(max_length=20)),
                ('companyOwnerName', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('contact', models.CharField(max_length=10)),
                ('companyLogo', models.ImageField(upload_to='img')),
            ],
            options={
                'db_table': 'ComapnyInfo',
            },
        ),
        migrations.AlterField(
            model_name='candidateinfo',
            name='email',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
