# Generated by Django 3.2.15 on 2022-08-23 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Adminapp', '0002_auto_20220819_0718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=20)),
                ('lastName', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254, null=True, unique=True)),
                ('password', models.CharField(max_length=15)),
                ('mobileNo', models.CharField(max_length=10)),
                ('AadharNo', models.CharField(max_length=16)),
            ],
            options={
                'db_table': 'EmployeeInfo',
            },
        ),
    ]
